version: 2

before:
  hooks:
    - go mod download

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - Merge branch
      - Merge pull request

builds:
  - id: darwin-amd64
    main: ./
    binary: slack-luxafor
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: darwin-arm64
    main: ./
    binary: slack-luxafor
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: slack-luxafor
    ids:
      - darwin-amd64
      - darwin-arm64
    files:
      - README.md
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}"
env_files:
  github_token: .release-env
release:
  github:
    owner: dsdeboer
    name: slack-luxafor
  prerelease: auto
  draft: false